// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnfgqtdtugfhykkzpozj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZmdxdGR0dWdmaHlra3pwb3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTA1MzcsImV4cCI6MjA1NTQ4NjUzN30.F1gpDGtwTyemrVTk-LaWElOs3UYyxJBe-0QDnU4Gwbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);